Repository Andrewnt219/rent-near-me, pull requests merged in 2021-11, with the labels that each got.

#103 Feature: Collect client IP and IP location on login and change password
  package.json
  src/models/api/entities/Profile/LoginHistory/LoginHistory.ts
  src/models/api/entities/Profile/PasswordUpdateHistory/PasswordUpdateHistory.ts
  src/pages/api/user/changePassword.ts
  src/pages/api/user/login.ts
  src/utils/api/ip-address-utils.ts
  src/utils/api/user-ip-locator.ts
  yarn.lock
Labels: type: feature, area: backend, priority: nice to have

#104 Refactor LayoutProvider to ModalProvider
  src/models/ChangePasswordPayload.ts
  src/models/LoginPayload.ts
  src/modules/layouts/DefaultLayout.tsx
  src/modules/layouts/components/HomeNavBar/HomeNavBar.tsx
  src/modules/layouts/components/UserMenu/UserMenu.tsx
  src/modules/user-auth/components/LoginForm/LoginForm.tsx
  src/modules/user-auth/components/LoginForm/useLoginForm.ts
  src/modules/user-auth/components/RegisterForm/RegisterForm.tsx
  src/modules/user-auth/components/RegisterForm/useRegisterForm.ts
  src/modules/user-auth/utils/AuthGuard/AuthGuard.tsx
  src/pages/_app.tsx
  src/services/AuthApi.ts
  src/ui/Modal/ModalContext.tsx
  src/utils/platform-utils.ts
Labels: area: frontend, type: refactor, priority: asap

#109 Fix profile not ready when it does not exist and is being validated
  src/modules/user-auth/hooks/useUserProfile.ts
Labels: type: bug & fix, area: frontend, priority: urgent

#112 feat: sync states between layouts
  @types/common.d.ts
  @types/next.d.ts
  src/modules/account/layouts/AccountPageLayout/AccountPageLayout.tsx
  src/modules/account/layouts/PaymentSettingPageLayout/PaymentSettingPageLayout.tsx
  src/modules/layouts/DefaultLayout.tsx
  src/pages/_app.tsx
  src/pages/account/index.tsx
  src/pages/account/payments/payment-methods.tsx
  src/pages/account/payments/payout-methods.tsx
  src/pages/account/payments/tax-info.tsx
  src/pages/account/profile.tsx
  src/pages/account/security.tsx
  src/pages/index.tsx
Labels: type: bug & fix, area: frontend

#113 Add Button-like Link components
  src/modules/layouts/DocsLayout.tsx
  src/modules/layouts/components/HomeNavBar/HomeNavBar.tsx
  src/modules/layouts/components/UserMenu/UserMenu.tsx
  src/pages/account/index.tsx
  src/pages/docs/button-and-link.tsx
  src/pages/docs/snackbar.tsx
  src/ui/Button/Button.tsx
  src/ui/Button/Link.tsx
  src/ui/Button/styles.tsx
Labels: type: feature, area: frontend, priority: asap

#115 Add sending verification email to user
  locales/en-us/account.json
  locales/en-us/common.json
  package.json
  src/modules/account/components/EmailActionField/EmailActionField.tsx
  src/modules/account/components/SendEmailVerificationButton/SendEmailVerificationButton.tsx
  src/pages/account/payments/payment-methods.tsx
  src/services/AuthApi.ts
  src/ui/Button/Button.tsx
  src/ui/Button/Link.tsx
  src/ui/Button/styles.tsx
  src/ui/Snackbar/Snackbar.tsx
  yarn.lock
Labels: type: feature, area: frontend, priority: must have
